export const PROMO_TOTAL_SPOTS = 20;
export const PROMO_CLAIMED_SPOTS = 14;
export const PROMO_REMAINING_SPOTS = PROMO_TOTAL_SPOTS - PROMO_CLAIMED_SPOTS;
export const PROMO_PROGRESS = Math.round((PROMO_CLAIMED_SPOTS / PROMO_TOTAL_SPOTS) * 100);
